# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='', upload_to='hiren'),
            preserve_default=False,
        ),
    ]
