# Generated by Django 2.0.2 on 2018-02-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
    ]
