# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
