# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20170405_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='direction',
        ),
        migrations.AddField(
            model_name='direction',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipe.Recipe'),
            preserve_default=False,
        ),
    ]
