# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20170405_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='meal',
            field=models.CharField(choices=[('Mai', 'Main Course'), ('Sna', 'Snacks'), ('Bre', 'Breakfast'), ('Sid', 'Side Dishes'), ('Des', 'Dessert'), ('Cak', 'Cake and Baking'), ('Dri', 'Drinks'), ('Oth', 'Other')], default='Oth', max_length=3),
        ),
    ]
