# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 04:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20170407_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='step',
        ),
        migrations.RemoveField(
            model_name='direction',
            name='timer',
        ),
    ]
