# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20170408_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='direction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredient',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Direction',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
